phone_display: '0540 531 19 68'
phone_link: 'tel:+905405311968'
email: info@fhmgroup.com.tr
email_link: 'mailto:info@fhmgroup.com.tr'
address: '272. Sk. Gündoğan Sit. B Blok No: 7/B Kayapınar/Diyarbakır'
working_hours: 'Hafta içi 08:30 - 18:30'
whatsapp_url: 'https://wa.me/905405311968'
